### ISSUE TITLE
수정 필요

### ISSUE THREAD

**Issue by 97kim** [haedal-uni/haedal-uni.github.io#1]
https://github.com/haedal-uni/haedal-uni.github.io/blob/e63733cb5c43665bbfd6943effcf70852e261432/_config.yml#L199

97kim 무엇? haedal-uni로 바꾸세욧!

<img width="935" alt="스크린샷 2022-07-21 오전 10 31 09" src="https://user-images.githubusercontent.com/64389162/180110386-01efa5ce-4119-4e94-a016-cbe8df3ca381.png">

제 리포지토리에 온단 말이에욧!

**Comment by haedal-uni** [comment]
바꿨습니닿😄
